package ModuloVenta;

import DTOs.ProductoDTO;
import Interface.IRegistroVenta;
import RegistroVentaException.RegistroException;
import control.ControlNavegacion;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class BusquedaProducto extends javax.swing.JFrame {
    LinkedList<PanelBusquedaProducto> panelBusquedaProducto;
    List<ProductoDTO> productos;
    IRegistroVenta manejadorVenta;
    
    /**
     * Creates new form BusquedaManual
     * @param manejadorVenta
     */
    public BusquedaProducto(IRegistroVenta manejadorVenta) {
        this.manejadorVenta = manejadorVenta;
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("Busqueda de Producto");

        this.lbl_ID.setText("ID: 00000000000");
        this.panelBusquedaProducto = new LinkedList<>();
        
        
        
    }

    public void busquedaProducto(String busqueda) throws RegistroException {
//        productos = manejadorVenta.buscarProductos(busqueda);
//        
//        // Limpiar antes de agregar nuevos paneles
//        this.panelBusquedaProducto.clear();
//        this.panelCambiante.removeAll();
//        this.panelCambiante.revalidate();
//        this.panelCambiante.repaint();
//        
//        for (ProductoDTO producto : productos) {
//            ProductoDTO producto4 = new ProductoDTO("gorra", "44577", "NY", "negra");
//            PanelBusquedaProducto panel = new PanelBusquedaProducto(manejadorVenta, producto4);
//            panelBusquedaProducto.add(panel);
//        }
//        
//        for (PanelBusquedaProducto panelProducto : panelBusquedaProducto) {
//            panelCambiante.add(panelProducto);
//        }
//        
//        this.panelCambiante.revalidate();
//        this.panelCambiante.repaint();
        
        ProductoDTO producto1 = new ProductoDTO("gorra", "44577", "NY", "negra");
        PanelBusquedaProducto productoPanel1 = new PanelBusquedaProducto(manejadorVenta, producto1);
        ProductoDTO producto2 = new ProductoDTO("Lentes de sol", "123456", "Gucci", "azules");
        PanelBusquedaProducto productoPanel2 = new PanelBusquedaProducto(manejadorVenta, producto2);
        panelBusquedaProducto.add(productoPanel1);
        panelBusquedaProducto.add(productoPanel2);
        
        for (PanelBusquedaProducto panelProducto : panelBusquedaProducto) {
            panelCambiante.add(panelProducto);
        }
        this.panelCambiante.revalidate();
        this.panelCambiante.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lbl_ID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();
        panelCambiante = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscarProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelSuperior.setBackground(new java.awt.Color(103, 80, 164));
        panelSuperior.setPreferredSize(new java.awt.Dimension(800, 50));

        lbl_ID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lbl_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID.setText("ID: 00000000000");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 605));

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelProductos.setPreferredSize(new java.awt.Dimension(800, 603));
        panelProductos.setLayout(new java.awt.BorderLayout());
        panelProductos.add(panelCambiante, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(panelProductos);

        btnRegresar.setBackground(new java.awt.Color(255, 186, 186));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(103, 80, 164));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search (1).png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(30, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscarProducto.setBackground(new java.awt.Color(208, 188, 255));
        txtBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscarProducto.setText("Buscar Producto");
        txtBuscarProducto.setPreferredSize(new java.awt.Dimension(130, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.getInstance().irACarritoCompra();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            this.busquedaProducto(txtBuscarProducto.getText());
        } catch (RegistroException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar el producto: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
