package ModuloVenta;

import DTOs.ProductoVentaDTO;
import Inicio.InicioSesion;
import Interface.IRegistroVenta;
import RegistroVentaException.RegistroException;
import control.ControlNavegacion;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class CarritoCompra extends javax.swing.JFrame {

    IRegistroVenta controlVenta;
    List<ProductoVentaDTO> carritoGlobal;
    private static CarritoCompra instancia;
    LinkedList<PanelProductosCarrito> panelesProductoCarrito;
    int cantidadProductos = 0;
    double subtotalProductos = 0;
    double impuestosProductos = 0;
    double totalProductos = 0;

    /**
     * Creates new form CarritoCompra
     *
     * @param controlVenta
     */
    public CarritoCompra(IRegistroVenta controlVenta) {
        initComponents();

        this.controlVenta = controlVenta;
        setTitle("Carrito de compra"); // nombre venata
        panelesProductoCarrito = new LinkedList<>();
        carritoGlobal = new ArrayList<>();

        cantidadProductos = 0;
        subtotalProductos = 0;
        impuestosProductos = 0;
        totalProductos = 0;

        lblCantProductos.setText(Integer.toString(cantidadProductos));
        lblSubProductos.setText(Double.toString(subtotalProductos));
        lblImpuestos.setText(Double.toString(impuestosProductos));
        totalJlabel.setText(Double.toString(totalProductos));
    }

    public static CarritoCompra getInstance(IRegistroVenta controlVenta) {
        if (instancia == null) {
            instancia = new CarritoCompra(controlVenta);
        }
        return instancia;
    }

    public List<ProductoVentaDTO> getCarritoGlobal() {
        return carritoGlobal;
    }

    public LinkedList<PanelProductosCarrito> getPanelesProductoCarrito() {
        return panelesProductoCarrito;
    }

    public void setPanelesProductoCarrito(LinkedList<PanelProductosCarrito> panelesProductoCarrito) {
        this.panelesProductoCarrito = panelesProductoCarrito;
    }

    public JPanel getPanelCambiante() {
        return panelCambiante;
    }

    public void cargarCarrito() {
        lblID.setText("ID: " + InicioSesion.getInstance().getIdCuenta());
        System.out.println("Se llamó a cargarCarrito()");
        cantidadProductos = 0;
        subtotalProductos = 0;
        impuestosProductos = 0;
        totalProductos = 0;

        panelesProductoCarrito.clear();
        panelCambiante.removeAll();

        System.out.println("Carrito tiene " + carritoGlobal.size() + " productos");
        for (ProductoVentaDTO producto : carritoGlobal) {
            cantidadProductos += producto.getCantidad();
            subtotalProductos += producto.getCantidad() * producto.getPrecioUnitario();

            PanelProductosCarrito panel = new PanelProductosCarrito(controlVenta, panelCambiante, producto);
            panelesProductoCarrito.add(panel);
        }

        impuestosProductos = subtotalProductos * 0.06;
        totalProductos = subtotalProductos + impuestosProductos;

        for (PanelProductosCarrito panelProducto : panelesProductoCarrito) {
            panelCambiante.add(panelProducto);
        }

        panelCambiante.setLayout(new BoxLayout(panelCambiante, BoxLayout.Y_AXIS));
        panelCambiante.revalidate();
        panelCambiante.repaint();

        lblCantProductos.setText(Integer.toString(cantidadProductos));
        lblSubProductos.setText(String.format("%.2f", subtotalProductos));
        lblImpuestos.setText(String.format("%.2f", impuestosProductos));
        totalJlabel.setText(String.format("%.2f", totalProductos));
    }

    public void limpiarCarrito() {
        this.carritoGlobal = new LinkedList<>();
        this.panelesProductoCarrito = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        panelResumen = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        cantidadJLabel = new javax.swing.JLabel();
        subtotalJlabel = new javax.swing.JLabel();
        impuestosJLabel = new javax.swing.JLabel();
        separarTotal = new javax.swing.JSeparator();
        Jlabel0 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        lblSubProductos = new javax.swing.JLabel();
        lblImpuestos = new javax.swing.JLabel();
        lblCantProductos = new javax.swing.JLabel();
        totalJlabel = new javax.swing.JLabel();
        ScrollProductosCarrito = new javax.swing.JScrollPane();
        PanelProductosScroll = new javax.swing.JPanel();
        panelCambiante = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelResumen.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cantidadJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantidadJLabel.setText("Cantidad productos:");

        subtotalJlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subtotalJlabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subtotalJlabel.setText("Subtotal:");

        impuestosJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        impuestosJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        impuestosJLabel.setText("Impuestos:");

        separarTotal.setForeground(new java.awt.Color(0, 0, 0));

        Jlabel0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Jlabel0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jlabel0.setText("Total:");

        btnCancelar.setBackground(new java.awt.Color(255, 186, 186));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(196, 39));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Resumen");

        btnPago.setBackground(new java.awt.Color(103, 80, 164));
        btnPago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPago.setForeground(new java.awt.Color(255, 255, 255));
        btnPago.setText("Proceder a Pago");
        btnPago.setPreferredSize(new java.awt.Dimension(196, 39));
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        lblSubProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubProductos.setText("subtotal");

        lblImpuestos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImpuestos.setText("impuestos");

        lblCantProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantProductos.setText("num");

        totalJlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalJlabel.setText("total");

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separarTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelResumenLayout.createSequentialGroup()
                                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResumenLayout.createSequentialGroup()
                                            .addComponent(impuestosJLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblImpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResumenLayout.createSequentialGroup()
                                            .addComponent(subtotalJlabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblSubProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResumenLayout.createSequentialGroup()
                                            .addComponent(cantidadJLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblCantProductos)))
                                    .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResumenLayout.createSequentialGroup()
                                            .addComponent(Jlabel0)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(totalJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(90, 90, 90))
                    .addGroup(panelResumenLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadJLabel)
                    .addComponent(lblCantProductos))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalJlabel)
                    .addComponent(lblSubProductos))
                .addGap(33, 33, 33)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(impuestosJLabel)
                    .addComponent(lblImpuestos))
                .addGap(320, 320, 320)
                .addComponent(separarTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel0)
                    .addComponent(totalJlabel))
                .addGap(28, 28, 28)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PanelProductosScroll.setLayout(new java.awt.BorderLayout());

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        PanelProductosScroll.add(panelCambiante, java.awt.BorderLayout.CENTER);

        ScrollProductosCarrito.setViewportView(PanelProductosScroll);

        panelSuperior.setBackground(new java.awt.Color(103, 80, 164));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID: 00000000");

        txtBuscarProducto.setBackground(new java.awt.Color(208, 188, 255));
        txtBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscarProducto.setText("Buscar Producto");
        txtBuscarProducto.setPreferredSize(new java.awt.Dimension(130, 27));

        btnBuscar.setBackground(new java.awt.Color(103, 80, 164));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search (1).png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(30, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(ScrollProductosCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollProductosCarrito)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(panelResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCarrito();
        ControlNavegacion.getInstance().irAMenuPrincipal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        if (carritoGlobal.isEmpty()) {
            System.out.println(carritoGlobal.size() + " productos");
            JOptionPane.showMessageDialog(this, "El carrito esta vacio");
        } else {
            ControlNavegacion.getInstance().irASeleccionMetodoPago();
        }
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            ControlNavegacion.getInstance().irABusquedaProducto(txtBuscarProducto.getText());
        } catch (RegistroException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar el producto: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel0;
    private javax.swing.JPanel PanelProductosScroll;
    private javax.swing.JScrollPane ScrollProductosCarrito;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPago;
    private javax.swing.JLabel cantidadJLabel;
    private javax.swing.JLabel impuestosJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantProductos;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblSubProductos;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JSeparator separarTotal;
    private javax.swing.JLabel subtotalJlabel;
    private javax.swing.JLabel totalJlabel;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
