package ModuloVenta;

import DTOs.ProductoVentaDTO;
import Interface.IRegistroVenta;
import javax.swing.JPanel;

/**
 * Esta clase Panel sirve para crear multiples instancias de este objeto con los
 * datos de los ProductosDTO
 *
 * @author gamae
 */
public class PanelProductosCarrito extends JPanel {

    int cantidad;
    double importe;
    double precio;
    ProductoVentaDTO producto;
    JPanel panelCambiante;
    IRegistroVenta controlVenta;

    /**
     * Creates new form JpanelProductosBO
     *
     * @param panel
     * @param producto
     */
    public PanelProductosCarrito(IRegistroVenta controlVenta, JPanel panel, ProductoVentaDTO producto) {
        panelCambiante = panel;
        this.producto = producto;
        this.controlVenta = controlVenta;
        initComponents();
        
        this.cantidad = producto.getCantidad();
        this.importe = producto.getCantidad() * producto.getPrecioUnitario();
        this.precio = producto.getPrecioUnitario();
        this.lblSKU.setText(producto.getProducto().getSKU());
        this.lblColor.setText(producto.getProducto().getColor());
        this.lblMarca.setText(producto.getProducto().getMarca());
        this.lblNombre.setText(producto.getProducto().getNombre());
        this.lblImporte.setText(Double.toString(importe));
        this.txtCantidadProducto.setText(Integer.toString(producto.getCantidad()));
        this.lblPrecio.setText(Double.toString(precio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblSKU = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        lblImporte = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnAumentarProducto = new javax.swing.JButton();
        btnDismunuirProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(520, 200));
        setMinimumSize(new java.awt.Dimension(520, 200));
        setPreferredSize(new java.awt.Dimension(520, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        lblMarca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblMarca.setText("Marca");
        add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, -1));

        lblColor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblColor.setText("Color");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        lblSKU.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSKU.setText("SKU");
        add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));

        lblCantidad.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblCantidad.setText("Cantidad");
        add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Importe");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        txtCantidadProducto.setEditable(false);
        txtCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadProducto.setText("CAntidad");
        add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 80, 30));

        lblImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporte.setText("0");
        add(lblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 60, 80, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Producto:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPrecio.setText("Precio");
        add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));

        btnAumentarProducto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnAumentarProducto.setText("+");
        btnAumentarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarProductoActionPerformed(evt);
            }
        });
        add(btnAumentarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 50, 30));

        btnDismunuirProducto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnDismunuirProducto.setText("-");
        btnDismunuirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismunuirProductoActionPerformed(evt);
            }
        });
        add(btnDismunuirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 30));

        btnEliminarProducto.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnEliminarProducto.setText("🗑");
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarProductoActionPerformed
        if (cantidad < producto.getProducto().getStock()) {
        cantidad++;
        producto.setCantidad(cantidad);
        txtCantidadProducto.setText(String.valueOf(cantidad));

        importe = cantidad * precio;
        lblImporte.setText(String.valueOf(importe));
        CarritoCompra.getInstance(controlVenta).cargarCarrito();
        }
    }//GEN-LAST:event_btnAumentarProductoActionPerformed

    private void btnDismunuirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismunuirProductoActionPerformed
        if (cantidad > 1) {
            cantidad--;
            producto.setCantidad(cantidad);
            txtCantidadProducto.setText(String.valueOf(cantidad));

            importe = cantidad * precio;
            lblImporte.setText(String.valueOf(importe));
            CarritoCompra.getInstance(controlVenta).cargarCarrito();
        }
    }//GEN-LAST:event_btnDismunuirProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        CarritoCompra.getInstance(controlVenta).getCarritoGlobal().remove(producto);
        panelCambiante.remove(this);
        panelCambiante.revalidate(); // Actualizar diseño
        panelCambiante.repaint(); // Redibujar
    }//GEN-LAST:event_btnEliminarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentarProducto;
    private javax.swing.JButton btnDismunuirProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JTextField txtCantidadProducto;
    // End of variables declaration//GEN-END:variables
}
