package ModuloVenta;

import DTOs.ProductoDTO;
import DTOs.ProductoVentaDTO;
import Interface.IRegistroVenta;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class PanelBusquedaProducto extends javax.swing.JPanel {

    IRegistroVenta controlVenta;
    LinkedList<PanelProductosCarrito> panelesProductoCarrito;
    ProductoDTO productoDTO;

    /**
     * Creates new form PanelBusquedaProducto
     *
     * @param controlVenta
     * @param productoDTO
     */
    public PanelBusquedaProducto(IRegistroVenta controlVenta, ProductoDTO productoDTO) {
        this.controlVenta = controlVenta;
        this.productoDTO = productoDTO;
        initComponents();
        this.lblNombre.setText(productoDTO.getNombre());
        this.lblMarca.setText(productoDTO.getMarca());
        this.lblColor.setText(productoDTO.getColor());
        this.lblSKU.setText(productoDTO.getSKU());
        this.lblPrecio.setText(Double.toString(productoDTO.getPrecio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblSKU = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnAgregarCarrito = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(800, 182));
        setMinimumSize(new java.awt.Dimension(800, 182));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 182));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarca.setText("Marca");
        add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, -1));

        lblProducto.setText("Producto");
        add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, 65, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, -1));

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblColor.setText("Color");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, -1));

        lblSKU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSKU.setText("SKU");
        add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecio.setText("Precio");
        add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, -1));

        btnAgregarCarrito.setBackground(new java.awt.Color(103, 80, 164));
        btnAgregarCarrito.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });
        add(btnAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 56, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        ProductoDTO producto = new ProductoDTO("Lentes de sol", "123456", "Gucci", "azules");
        ProductoVentaDTO productoVenta = new ProductoVentaDTO(producto, 1, productoDTO.getPrecio());

        PanelProductosCarrito productoPanel = new PanelProductosCarrito(CarritoCompra.getInstance(controlVenta).getPanelCambiante(), productoVenta);

        panelesProductoCarrito = CarritoCompra.getInstance(controlVenta).getPanelesProductoCarrito();
        panelesProductoCarrito.add(productoPanel);
        CarritoCompra.getInstance(controlVenta).setPanelesProductoCarrito(panelesProductoCarrito);
        JOptionPane.showMessageDialog(this, "Producto registrado en el carrito: ");
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSKU;
    // End of variables declaration//GEN-END:variables
}
