/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesBusquedaManual;

import DTOs.ProductoDTO;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author gamae
 */
public class panelProductosDTO extends JPanel {

    /**
     * Creates new form JpanelProductosBO
     */
    public panelProductosDTO(ProductoDTO producto, int cantidad, int importe) {
        initComponents();
        this.SKULBL= new JLabel(producto.getSku());     
        this.colorLBL=new JLabel(producto.getColor());
        this.marcaLBL=new JLabel(producto.getMarca());
        this.nombreLBL=new JLabel(producto.getNombre());
        this.importeProductoLBL=new JLabel(Integer.toString(importe));
        this.cantidadProductoLBL=new JLabel(Integer.toString(cantidad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLBL = new javax.swing.JLabel();
        marcaLBL = new javax.swing.JLabel();
        colorLBL = new javax.swing.JLabel();
        SKULBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        importeProductoLBL = new javax.swing.JLabel();
        cantidadProductoLBL = new javax.swing.JLabel();

        nombreLBL.setText("jLabel1");

        marcaLBL.setText("jLabel2");

        colorLBL.setText("jLabel3");

        SKULBL.setText("jLabel4");

        jLabel1.setText("Cantidad");

        jLabel2.setText("Importe");

        importeProductoLBL.setText("jLabel3");

        cantidadProductoLBL.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nombreLBL)
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cantidadProductoLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importeProductoLBL)
                            .addComponent(jLabel2))
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SKULBL)
                            .addComponent(colorLBL)
                            .addComponent(marcaLBL))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLBL)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(marcaLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importeProductoLBL)
                    .addComponent(cantidadProductoLBL))
                .addGap(9, 9, 9)
                .addComponent(colorLBL)
                .addGap(18, 18, 18)
                .addComponent(SKULBL)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SKULBL;
    private javax.swing.JLabel cantidadProductoLBL;
    private javax.swing.JLabel colorLBL;
    private javax.swing.JLabel importeProductoLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel marcaLBL;
    private javax.swing.JLabel nombreLBL;
    // End of variables declaration//GEN-END:variables
}
