package ModuloAlmacen.GestionProveedores;

import DTOs.ProveedorTablaDTO;
import Excepciones.ProveedorException;
import Implementaciones.IManejadorProveedor;
import Utilidades.JButtonCellEditor;
import Utilidades.JButtonRenderer;
import control.ControlNavegacion;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.bson.types.ObjectId;

/**
 * ProveedoresPanelListado.java
 *
 * Esta panel contiene la tabla con los proveedores registrados.
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class ProveedoresPanelListado extends javax.swing.JPanel {

    private static ProveedoresPanelListado instancia;
    private final IManejadorProveedor controlProveedor;

    /**
     * Creates new form ProveedoresPanelListado
     *
     * @param controlProveedor
     */
    public ProveedoresPanelListado(IManejadorProveedor controlProveedor) {
        this.controlProveedor = controlProveedor;
        initComponents();
        configurarBotonesTabla();
    }

    public static ProveedoresPanelListado getInstance(IManejadorProveedor controlProveedor) {
        if (instancia == null) {
            instancia = new ProveedoresPanelListado(controlProveedor);
        }
        return instancia;
    }

    private void configurarBotonesTabla() {
        TableColumnModel modeloColumnas = tablaProveedores.getColumnModel();

        // Botón Detalles
        ActionListener onDetallesClickListener = e -> {
            try {
                int fila = Integer.parseInt(e.getActionCommand());
                String idStr = tablaProveedores.getValueAt(fila, 0).toString();
                ObjectId id = new ObjectId(idStr);
                ControlNavegacion.getInstance().mostrarPanelProveedorDetalles(id);
            } catch (ProveedorException ex) {
                System.out.println(ex.getMessage());
            }
        };
        int indiceColumnaDetalles = 5;
        modeloColumnas.getColumn(indiceColumnaDetalles)
                .setCellRenderer(new JButtonRenderer("Detalles"));
        modeloColumnas.getColumn(indiceColumnaDetalles)
                .setCellEditor(new JButtonCellEditor("Detalles", onDetallesClickListener));

        // Botón Editar
        ActionListener onEditarClickListener = e -> {
            try {
                int fila = Integer.parseInt(e.getActionCommand());
                String idStr = tablaProveedores.getValueAt(fila, 0).toString();
                ObjectId id = new ObjectId(idStr);
                ControlNavegacion.getInstance().mostrarPanelProveedorEditar(id);
            } catch (ProveedorException ex) {
                System.out.println(ex.getMessage());
            }
        };
        int indiceColumnaEditar = 6;
        modeloColumnas.getColumn(indiceColumnaEditar)
                .setCellRenderer(new JButtonRenderer("Editar"));
        modeloColumnas.getColumn(indiceColumnaEditar)
                .setCellEditor(new JButtonCellEditor("Editar", onEditarClickListener));
    }

    public void cargarListaProveedores() {
        List<ProveedorTablaDTO> listaProveedores = controlProveedor.obtenerDatosParaTabla();

        DefaultTableModel modelo = controlProveedor.obtenerModeloTablaProveedores(listaProveedores);

        tablaProveedores.setModel(modelo); // Establece el nuevo modelo
        configurarBotonesTabla();          // Restablece los renderizadores y editores
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCambiante = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        btnAñadir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));

        tablaProveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Correo Electrónico", "Estado", "Detalles", "Editar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        btnAñadir.setBackground(new java.awt.Color(103, 80, 164));
        btnAñadir.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir Proveedor");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(243, 183, 183));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout panelCambianteLayout = new javax.swing.GroupLayout(panelCambiante);
        panelCambiante.setLayout(panelCambianteLayout);
        panelCambianteLayout.setHorizontalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                    .addGroup(panelCambianteLayout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCambianteLayout.setVerticalGroup(
            panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCambianteLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.getInstance().mostrarMenuAlmacen();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        ControlNavegacion.getInstance().mostrarPanelProveedorNuevo();
    }//GEN-LAST:event_btnAñadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
