package ModuloAlmacen.GestionInventario;

import DTOs.MovimientoDTO;
import ModuloAdministracion.GestionProductos.*;
import DTOs.ProductoDTO;
import Excepciones.NegocioException;
import Exception.PersistenciaException;
import Inicio.InicioSesion;
import Interfaces.IMovimientoBO;
import Interfaces.IProductoBO;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bson.types.ObjectId;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class InventarioPanelDisminuir extends javax.swing.JPanel {

    private final JPanel panelCambiante;
    private final JFrame pantalla;
    private final IMovimientoBO movimientoBO;
    private final IProductoBO productoBO;
    private ProductoDTO productoDTO;
    private final ObjectId idProducto;
    private int cantidad;

    /**
     * Creates new form PanelEditarProducto
     *
     * @param pantalla
     * @param panelCambiante
     * @param movimientoBO
     * @param productoBO
     * @param idProducto
     */
    public InventarioPanelDisminuir(JFrame pantalla, JPanel panelCambiante, IMovimientoBO movimientoBO, IProductoBO productoBO, ObjectId idProducto) {
        initComponents();
        this.panelCambiante = panelCambiante;
        this.pantalla = pantalla;
        this.movimientoBO = movimientoBO;
        this.productoBO = productoBO;
        this.idProducto = idProducto;
        this.cargarDatos();
    }

    private ProductoDTO obtenerProducto(ObjectId id) throws NegocioException {
        return productoBO.buscarProductoPorId(id);
    }

    private void cargarDatos() {
        try {
            productoDTO = this.obtenerProducto(this.idProducto);
            cantidad = productoDTO.getStock();
        } catch (NegocioException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
        this.lblSKU.setText(this.productoDTO.getSKU());
        this.lblNombre.setText(this.productoDTO.getNombre());
        this.lblMarca.setText(this.productoDTO.getMarca());
        this.lblColor.setText(this.productoDTO.getColor());
        this.lblPrecio.setText(String.valueOf(this.productoDTO.getPrecio()));
        this.lblStock.setText(String.valueOf(cantidad));
        this.txtCantidadProducto.setText(String.valueOf(cantidad));
    }

    public void realizarMovimiento() throws NegocioException, PersistenciaException {
        MovimientoDTO movimientoDTO = new MovimientoDTO();
        movimientoDTO.setIdCuenta(InicioSesion.getInstance().getIdCuenta());
        movimientoDTO.setUsuarioResponsable(InicioSesion.getInstance().getNombreUsuario());
        movimientoDTO.setCodigoProducto(productoDTO.getCodigo());
        movimientoDTO.setTipoOperacion("Perdida");
        movimientoDTO.setCantidad(cantidad);
        movimientoDTO.setMotivo(txtMotivo.getText());

        try {
            MovimientoDTO resultado = movimientoBO.registrarMovimiento(movimientoDTO);
            productoBO.actualizarProducto(productoDTO);
            JOptionPane.showMessageDialog(this, "Movimienvo registrado con éxito con el ID: " + resultado.getId());
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar el movimiento: " + e.getMessage());
        }
    }

    public void volver() {
        InventarioPanelListado panelListado = new InventarioPanelListado(pantalla, panelCambiante, movimientoBO, productoBO);
        panelCambiante.setLayout(new BorderLayout());
        panelCambiante.removeAll();
        panelCambiante.add(panelListado, BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAumentarProducto = new javax.swing.JButton();
        btnDismunuirProducto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disminuir Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        btnVolver.setBackground(new java.awt.Color(103, 80, 164));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 459, 220, 50));

        btnEditar.setBackground(new java.awt.Color(103, 80, 164));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar Stock");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 459, 220, 50));

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMarca.setText("Marca");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 250, -1));

        txtCantidadProducto.setEditable(false);
        txtCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadProducto.setText("CAntidad");
        jPanel1.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 290, 70));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nombre");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Marca");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock actual");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 290, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Stock actual");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 290, -1));

        btnAumentarProducto.setBackground(new java.awt.Color(158, 255, 139));
        btnAumentarProducto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnAumentarProducto.setText("+");
        btnAumentarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAumentarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 70, 70));

        btnDismunuirProducto.setBackground(new java.awt.Color(243, 183, 183));
        btnDismunuirProducto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnDismunuirProducto.setText("-");
        btnDismunuirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismunuirProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDismunuirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Descripción");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 470, -1));

        lblSKU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSKU.setText("SKU");
        jPanel1.add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jPanel1.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 470, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SKU");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Color");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, -1));

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblColor.setText("Color");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 250, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Precio");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio.setText("Precio");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.volver();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            productoDTO.setStock(cantidad);
            this.realizarMovimiento();
            this.volver();
        } catch (NegocioException | PersistenciaException ex) {
            JOptionPane.showMessageDialog(this, "Movimienvo realizado con éxito");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAumentarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarProductoActionPerformed
        if (cantidad < productoDTO.getStock()) {
            cantidad++;
            txtCantidadProducto.setText(String.valueOf(cantidad));
            this.revalidate();
            this.repaint();
        }
    }//GEN-LAST:event_btnAumentarProductoActionPerformed

    private void btnDismunuirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismunuirProductoActionPerformed
        if (cantidad > 0) {
            cantidad--;
            txtCantidadProducto.setText(String.valueOf(cantidad));
            this.revalidate();
            this.repaint();
        }
    }//GEN-LAST:event_btnDismunuirProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentarProducto;
    private javax.swing.JButton btnDismunuirProducto;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblStock;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
