package ModuloAlmacen.GestionInventario;

import DTOs.MovimientoDTO;
import DTOs.ProductoDTO;
import Excepciones.NegocioException;
import Exception.PersistenciaException;
import Inicio.InicioSesion;
import Interfaces.IMovimientoBO;
import Interfaces.IProductoBO;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bson.types.ObjectId;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class InventarioPanelMovimientosDetalles extends javax.swing.JPanel {

    private final JPanel panelCambiante;
    private final JFrame pantalla;
    private final IMovimientoBO movimientoBO;
    private final IProductoBO productoBO;
    private MovimientoDTO movimientoDTO;
    private final ObjectId idMovimiento;
    private int cantidad;

    /**
     * Creates new form PanelEditarProducto
     *
     * @param pantalla
     * @param panelCambiante
     * @param movimientoBO
     * @param productoBO
     * @param idMovimiento
     */
    public InventarioPanelMovimientosDetalles(JFrame pantalla, JPanel panelCambiante, IMovimientoBO movimientoBO, IProductoBO productoBO, ObjectId idMovimiento) {
        initComponents();
        this.panelCambiante = panelCambiante;
        this.pantalla = pantalla;
        this.movimientoBO = movimientoBO;
        this.productoBO = productoBO;
        this.idMovimiento = idMovimiento;
        this.cargarDatos();
    }

    private MovimientoDTO obtenerMovimiento(ObjectId id) throws NegocioException {
        return movimientoBO.obtenerMovimientoPorId(id);
    }

    private void cargarDatos() {
        try {
            movimientoDTO = this.obtenerMovimiento(this.idMovimiento);
        } catch (NegocioException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
        
        this.lblID.setText(String.valueOf(this.movimientoDTO.getId()));
        this.lblFecha.setText(String.valueOf(this.movimientoDTO.getFecha()));
        this.lblCuenta.setText(this.movimientoDTO.getIdCuenta());
        this.lblResponsable.setText(this.movimientoDTO.getNombreProducto());
        this.lblProducto.setText(this.movimientoDTO.getNombreProducto());
        this.lblTipoOperacion.setText(this.movimientoDTO.getTipoOperacion());
        this.lblCantidad.setText(String.valueOf(this.movimientoDTO.getCantidad()));
        this.lblMotivo.setText(this.movimientoDTO.getMotivo());
    }

    public void volver() {
        InventarioPanelListado panelListado = new InventarioPanelListado(pantalla, panelCambiante, movimientoBO, productoBO);
        panelCambiante.setLayout(new BorderLayout());
        panelCambiante.removeAll();
        panelCambiante.add(panelListado, BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblResponsable = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTipoOperacion = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        btnVolver.setBackground(new java.awt.Color(103, 80, 164));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 459, 220, 60));

        lblResponsable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblResponsable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResponsable.setText("nombreResponsable");
        jPanel1.add(lblResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 310, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Producto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Responsable");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 310, -1));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("id");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 290, -1));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(153, 153, 153));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 520, -1));

        lblProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProducto.setText("Producto");
        jPanel1.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 300, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Tipo Operación");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 180, -1));

        lblTipoOperacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTipoOperacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoOperacion.setText("TipoOperacion");
        jPanel1.add(lblTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 310, -1));

        lblCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuenta.setText("idCuenta");
        jPanel1.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 310, -1));

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMotivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMotivo.setText("Motivo");
        jPanel1.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 610, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Motivo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCantidad.setText("Cantidad");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Cantidad");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.volver();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblTipoOperacion;
    // End of variables declaration//GEN-END:variables
}
