/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloAdministracion;

import BOs.ProductoBO;
import DAOs.Conexion;
import Excepciones.NegocioException;
import Interfaces.IProductoBO;
import Interfaz.IConexion;
import ModuloAdministracion.GestionProductos.PanelAdministradorMenu;
import ModuloAdministracion.GestionProductos.PanelListadoProductos;
import control.ControlNavegacion;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author gaspa
 */
public class AdministradorMenu extends javax.swing.JFrame {
    /**
     * Creates new form MenuPrincipal
     */
    public AdministradorMenu() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.llamarPanelMenu();
        
    }
    public final void llamarPanelMenu(){
        PanelAdministradorMenu panelAdmin = new PanelAdministradorMenu(PanelAdministradorMenu);
        PanelAdministradorMenu.setLayout(new BorderLayout());
        PanelAdministradorMenu.removeAll();
        PanelAdministradorMenu.add(panelAdmin,BorderLayout.CENTER);
        PanelAdministradorMenu.revalidate();
        PanelAdministradorMenu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lbl_ID = new javax.swing.JLabel();
        panelSuperior1 = new javax.swing.JPanel();
        lbl_ID1 = new javax.swing.JLabel();
        PanelAdministradorMenu = new javax.swing.JPanel();

        panelSuperior.setBackground(new java.awt.Color(103, 80, 164));
        panelSuperior.setPreferredSize(new java.awt.Dimension(800, 50));

        lbl_ID.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lbl_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID.setText("ID: 00000000000");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        panelSuperior1.setBackground(new java.awt.Color(103, 80, 164));
        panelSuperior1.setPreferredSize(new java.awt.Dimension(800, 50));

        lbl_ID1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lbl_ID1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID1.setText("ID: 00000000000");

        javax.swing.GroupLayout panelSuperior1Layout = new javax.swing.GroupLayout(panelSuperior1);
        panelSuperior1.setLayout(panelSuperior1Layout);
        panelSuperior1Layout.setHorizontalGroup(
            panelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperior1Layout.setVerticalGroup(
            panelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAdministradorMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelAdministradorMenu.setForeground(new java.awt.Color(255, 255, 255));
        PanelAdministradorMenu.setMinimumSize(new java.awt.Dimension(1000, 550));
        PanelAdministradorMenu.setPreferredSize(new java.awt.Dimension(1000, 550));
        PanelAdministradorMenu.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelAdministradorMenuLayout = new javax.swing.GroupLayout(PanelAdministradorMenu);
        PanelAdministradorMenu.setLayout(PanelAdministradorMenuLayout);
        PanelAdministradorMenuLayout.setHorizontalGroup(
            PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelAdministradorMenuLayout.setVerticalGroup(
            PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAdministradorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelSuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelAdministradorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdministradorMenu;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_ID1;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelSuperior1;
    // End of variables declaration//GEN-END:variables
}
