/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionVendedores;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author melis
 */
public class ListadoVendedores extends javax.swing.JFrame {
// private JTable tablaVendedores;

    private DefaultTableModel modelTabla;

    /**
     * Creates new form ListadoVendedores
     */
    public ListadoVendedores() {
        /*Barra de opciones*/
        // JPanel sidebar = new JPanel(new GridLayout(5, 1, 5, 5));
        sidebar.add(BotonAgregarVendedor,BorderLayout.CENTER);
        sidebar.add(BotonAltasyBajas,BorderLayout.CENTER);
        sidebar.add(BotonGenerarInforme,BorderLayout.CENTER);

        add(sidebar, BorderLayout.WEST);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        BotonAltasyBajas = new javax.swing.JButton();
        BotonAgregarVendedor = new javax.swing.JButton();
        BotonGenerarInforme = new javax.swing.JButton();
        PanelListadoVendedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListadoVendedores");
        setPreferredSize(new java.awt.Dimension(800, 600));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonAltasyBajas.setBackground(new java.awt.Color(242, 242, 242));
        BotonAltasyBajas.setText("Altas y Bajas");
        BotonAltasyBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltasyBajasActionPerformed(evt);
            }
        });

        BotonAgregarVendedor.setBackground(new java.awt.Color(242, 242, 242));
        BotonAgregarVendedor.setText("+ Vendedor");
        BotonAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarVendedorActionPerformed(evt);
            }
        });

        BotonGenerarInforme.setBackground(new java.awt.Color(242, 242, 242));
        BotonGenerarInforme.setText("Generar Informe");
        BotonGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonAltasyBajas)
                            .addComponent(BotonAgregarVendedor)))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BotonGenerarInforme)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(BotonAltasyBajas)
                .addGap(49, 49, 49)
                .addComponent(BotonAgregarVendedor)
                .addGap(41, 41, 41)
                .addComponent(BotonGenerarInforme)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PanelListadoVendedores.setBackground(new java.awt.Color(255, 255, 255));

        jScrollBar1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jScrollBar1);

        javax.swing.GroupLayout PanelListadoVendedoresLayout = new javax.swing.GroupLayout(PanelListadoVendedores);
        PanelListadoVendedores.setLayout(PanelListadoVendedoresLayout);
        PanelListadoVendedoresLayout.setHorizontalGroup(
            PanelListadoVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoVendedoresLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelListadoVendedoresLayout.setVerticalGroup(
            PanelListadoVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListadoVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelListadoVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltasyBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltasyBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAltasyBajasActionPerformed

    private void BotonAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarVendedorActionPerformed

    private void BotonGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGenerarInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoVendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarVendedor;
    private javax.swing.JButton BotonAltasyBajas;
    private javax.swing.JButton BotonGenerarInforme;
    private javax.swing.JPanel PanelListadoVendedores;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
