/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionVendedores;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author melis
 */
public class PanelListadoVendedores extends javax.swing.JPanel {

    private JTable tablaVendedores;
    private DefaultTableModel modelTabla;
//private JTextField txtBusca;

    /**
     * Creates new form PanelListadoVendedores
     */
    public PanelListadoVendedores() {
        setLayout(new BorderLayout());
        /*Barra de opciones*/
        JPanel sidebar = new JPanel(new GridLayout(5, 1, 5, 5));
        sidebar.add(new JButton("Altas y Bajas"));
        sidebar.add(new JButton("+ Vendedor"));
        sidebar.add(new JButton("Generar Informe"));
        sidebar.add(new JButton("cerrar sesion"));

        add(sidebar, BorderLayout.WEST);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
