/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionVendedores;
import java.awt.*;
/**
 *
 * @author melis
 */
public class RegistrarVendedor extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVendedor
     */
    public RegistrarVendedor() {
       sideBar.add(BotonAgregarVendedor,BorderLayout.CENTER);
       sideBar.add(botonCancelarBoton,BorderLayout.CENTER);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        BotonAgregarVendedor = new javax.swing.JButton();
        botonCancelarBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelRFC = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        LabelFechaNacimiento = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        labelEstadoCivil = new javax.swing.JLabel();
        labelCurp = new javax.swing.JLabel();
        labelDelegacionMunicipio = new javax.swing.JLabel();
        labelCiudadLocalidad = new javax.swing.JLabel();
        cajaRFC = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        cajaApellido = new javax.swing.JTextField();
        cajaFechaNacimiento = new javax.swing.JTextField();
        cajaDomicilio = new javax.swing.JTextField();
        cajaEstadoCivil = new javax.swing.JTextField();
        cajaCURP = new javax.swing.JTextField();
        cajaDelegacionMunicipio = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        cajaCiudadLocalidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Vendedor");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        sideBar.setBackground(new java.awt.Color(255, 255, 255));
        sideBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonAgregarVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarVendedor.setText("Agregar Vendedor");
        BotonAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarVendedorActionPerformed(evt);
            }
        });

        botonCancelarBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonCancelarBoton.setText("Cancelar");
        botonCancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonAgregarVendedor))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botonCancelarBoton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(BotonAgregarVendedor)
                .addGap(34, 34, 34)
                .addComponent(botonCancelarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelRFC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelRFC.setText("RFC");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelNombre.setText("Nombre(s)");

        LabelFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelFechaNacimiento.setText("Fecha de Nacimiento");

        labelDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelDomicilio.setText("Domicilio");

        labelEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelEstadoCivil.setText("EStado civil");

        labelCurp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelCurp.setText("CURP");

        labelDelegacionMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelDelegacionMunicipio.setText("Delegacion o municipio");

        labelCiudadLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelCiudadLocalidad.setText("Ciudad o localidad");

        cajaRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaRFCActionPerformed(evt);
            }
        });

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });

        cajaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaApellidoActionPerformed(evt);
            }
        });

        cajaFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaFechaNacimientoActionPerformed(evt);
            }
        });

        cajaDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDomicilioActionPerformed(evt);
            }
        });

        cajaEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaEstadoCivilActionPerformed(evt);
            }
        });

        cajaCURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCURPActionPerformed(evt);
            }
        });

        cajaDelegacionMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDelegacionMunicipioActionPerformed(evt);
            }
        });

        labelApellido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelApellido.setText("Apellidos");

        cajaCiudadLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCiudadLocalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCiudadLocalidad)
                    .addComponent(labelNombre)
                    .addComponent(labelRFC)
                    .addComponent(labelApellido)
                    .addComponent(LabelFechaNacimiento)
                    .addComponent(labelDomicilio)
                    .addComponent(labelEstadoCivil)
                    .addComponent(labelCurp)
                    .addComponent(labelDelegacionMunicipio))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaDelegacionMunicipio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(cajaCURP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaDomicilio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaRFC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaCiudadLocalidad))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRFC)
                    .addComponent(cajaRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(cajaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFechaNacimiento)
                    .addComponent(cajaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDomicilio)
                    .addComponent(cajaDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoCivil)
                    .addComponent(cajaEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurp)
                    .addComponent(cajaCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaDelegacionMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDelegacionMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCiudadLocalidad)
                    .addComponent(cajaCiudadLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarVendedorActionPerformed

    private void botonCancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarBotonActionPerformed

    private void cajaDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDomicilioActionPerformed
        // TODO add your handling code here:
        String domicilio=cajaDomicilio.getText();
    }//GEN-LAST:event_cajaDomicilioActionPerformed

    private void cajaCURPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCURPActionPerformed
        // TODO add your handling code here:
        String curp;
        curp=cajaCURP.getText();
    }//GEN-LAST:event_cajaCURPActionPerformed

    private void cajaRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaRFCActionPerformed
        // TODO add your handling code here:
        String rfc=cajaRFC.getText();
    }//GEN-LAST:event_cajaRFCActionPerformed

    private void cajaDelegacionMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDelegacionMunicipioActionPerformed
        // TODO add your handling code here:
        String delegacion;
        delegacion=cajaDelegacionMunicipio.getText();
    }//GEN-LAST:event_cajaDelegacionMunicipioActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre=cajaNombre.getText();
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaApellidoActionPerformed
        // TODO add your handling code here:
        String apellido=cajaApellido.getText();
    }//GEN-LAST:event_cajaApellidoActionPerformed

    private void cajaFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaFechaNacimientoActionPerformed
        // TODO add your handling code here:
//        LocalDataTime fechaNacimiento=cajaFechaNacimiento;
    }//GEN-LAST:event_cajaFechaNacimientoActionPerformed

    private void cajaEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaEstadoCivilActionPerformed
        // TODO add your handling code here:
        String estadoCivil=cajaEstadoCivil.getText();
    }//GEN-LAST:event_cajaEstadoCivilActionPerformed

    private void cajaCiudadLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCiudadLocalidadActionPerformed
        // TODO add your handling code here:
        String localidad;
        localidad=cajaCiudadLocalidad.getText();
    }//GEN-LAST:event_cajaCiudadLocalidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarVendedor;
    private javax.swing.JLabel LabelFechaNacimiento;
    private javax.swing.JButton botonCancelarBoton;
    private javax.swing.JTextField cajaApellido;
    private javax.swing.JTextField cajaCURP;
    private javax.swing.JTextField cajaCiudadLocalidad;
    private javax.swing.JTextField cajaDelegacionMunicipio;
    private javax.swing.JTextField cajaDomicilio;
    private javax.swing.JTextField cajaEstadoCivil;
    private javax.swing.JTextField cajaFechaNacimiento;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaRFC;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCiudadLocalidad;
    private javax.swing.JLabel labelCurp;
    private javax.swing.JLabel labelDelegacionMunicipio;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRFC;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
