/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloAdministracion.GestionProductos;

import BOs.ProductoBO;
import BOs.VendedorBO;
import DAOs.Conexion;
import Interfaces.IProductoBO;
import Interfaces.IVendedorBO;
import Interfaz.IConexion;
import ModuloAdministracion.GestionVendedores.PanelListadoVendedores;
import control.ControlNavegacion;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author gaspa
 */
public class PanelAdministradorMenu extends javax.swing.JPanel {
    private final IProductoBO productoBO;
    private final IVendedorBO vendedoresBO;
    private final IConexion mongo;
    private final JPanel panelCambiante;
    /**
     * Creates new form PanelAdministradorMenu
     */
    public PanelAdministradorMenu(JPanel panelCambiante) {
        initComponents();
        this.mongo = new Conexion();
        this.productoBO = new ProductoBO();
        this.vendedoresBO = new VendedorBO();
        this.panelCambiante = panelCambiante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdministradorMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gestionProductosBTN = new javax.swing.JButton();
        gestionVendedoresBTN = new javax.swing.JButton();
        ReportesBTN = new javax.swing.JButton();
        promocionesBTN = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        PanelAdministradorMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelAdministradorMenu.setForeground(new java.awt.Color(255, 255, 255));
        PanelAdministradorMenu.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Menu Principal");

        gestionProductosBTN.setBackground(new java.awt.Color(103, 80, 164));
        gestionProductosBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gestionProductosBTN.setForeground(new java.awt.Color(255, 255, 255));
        gestionProductosBTN.setText("Gestion de Productos");
        gestionProductosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProductosBTNActionPerformed(evt);
            }
        });

        gestionVendedoresBTN.setBackground(new java.awt.Color(103, 80, 164));
        gestionVendedoresBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gestionVendedoresBTN.setForeground(new java.awt.Color(255, 255, 255));
        gestionVendedoresBTN.setText("Gestion de Vendedores");
        gestionVendedoresBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionVendedoresBTNActionPerformed(evt);
            }
        });

        ReportesBTN.setBackground(new java.awt.Color(103, 80, 164));
        ReportesBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReportesBTN.setForeground(new java.awt.Color(255, 255, 255));
        ReportesBTN.setText("Reportes");
        ReportesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesBTNActionPerformed(evt);
            }
        });

        promocionesBTN.setBackground(new java.awt.Color(103, 80, 164));
        promocionesBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        promocionesBTN.setForeground(new java.awt.Color(255, 255, 255));
        promocionesBTN.setText("Promociones y paquetes");

        btnCerrarSesion.setBackground(new java.awt.Color(243, 183, 183));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdministradorMenuLayout = new javax.swing.GroupLayout(PanelAdministradorMenu);
        PanelAdministradorMenu.setLayout(PanelAdministradorMenuLayout);
        PanelAdministradorMenuLayout.setHorizontalGroup(
            PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdministradorMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdministradorMenuLayout.createSequentialGroup()
                                .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gestionVendedoresBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gestionProductosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(promocionesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ReportesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        PanelAdministradorMenuLayout.setVerticalGroup(
            PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gestionProductosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReportesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAdministradorMenuLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(PanelAdministradorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(promocionesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestionVendedoresBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addComponent(btnCerrarSesion)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministradorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministradorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gestionProductosBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProductosBTNActionPerformed
        PanelListadoProductos panelMenuGestion = new PanelListadoProductos(panelCambiante, productoBO);
        panelCambiante.setLayout(new BorderLayout());
        panelCambiante.removeAll();
        panelCambiante.add(panelMenuGestion,BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_gestionProductosBTNActionPerformed

    private void ReportesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesBTNActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        ControlNavegacion.getInstance().irAMenuPrincipal();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void gestionVendedoresBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionVendedoresBTNActionPerformed
        PanelListadoVendedores panelVendedores = new PanelListadoVendedores(panelCambiante, vendedoresBO);
        panelCambiante.setLayout(new BorderLayout());
        panelCambiante.removeAll();
        panelCambiante.add(panelVendedores,BorderLayout.CENTER);
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_gestionVendedoresBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdministradorMenu;
    private javax.swing.JButton ReportesBTN;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton gestionProductosBTN;
    private javax.swing.JButton gestionVendedoresBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton promocionesBTN;
    // End of variables declaration//GEN-END:variables
}
